export const AUTH_MODAL_ACTION_TYPES = {
  OPEN_SIGN_IN_MODAL: "authModal/OPEN_SIGN_IN_MODAL",
  OPEN_SIGN_UP_MODAL: "authModal/OPEN_SIGN_UP_MODAL",
  CLOSE_AUTH_MODAL: "authModal/CLOSE_AUTH_MODAL",
};
